name: Test

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      CPU: i386
      PKG_CONFIG_PATH: /usr/lib/i386-linux-gnu/pkgconfig

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linux dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc pkg-config gcc-multilib g++-multilib
          sudo apt-get install -y libattr1-dev libfuse-dev
          sudo apt-get install -y libattr1-dev:i386 libfuse-dev:i386

      - name: Hack for 32bit
        run: |
          if [[ $CPU = i386 ]]; then mkdir ~/bin; fi
          if [[ $CPU = i386 ]]; then echo -e "#!/bin/bash\n$(which gcc) -m32 \"\$@\"" > ~/bin/gcc; fi
          if [[ $CPU = i386 ]]; then chmod 755 ~/bin/gcc; fi
          if [[ $CPU = i386 ]]; then echo -e "#!/bin/bash\n$(which g++) -m32 \"\$@\"" > ~/bin/g++; fi
          if [[ $CPU = i386 ]]; then chmod 755 ~/bin/g++; fi
          echo ~/bin > $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          test/ci-install.sh

      - name: Test
        run: |
          test/ci-test.sh
